{% set name = "dictlib" %}
{% set version = "1.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6aec0b3f1eb742497c14a181f673a976a0981e67210ee955b3e417a4e7d3c22f

build:
  noarch: python
  number: 3
  script: {{ PYTHON }} -m pip install .  -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - dictlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/srevenant/dictlib
  license: AGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Dictionary Library including good deep merge and dictionary as objects
  dev_url: https://github.com/srevenant/dictlib

extra:
  recipe-maintainers:
    - mxr-conda
    - Tata17
