travis:
  secure:
    BINSTAR_TOKEN: Ez1smYNuJ6S0PJNFPa3RPjQLbjUb/1jIXNpSnP45qX2PEsEin/MNgEQ0wGzaCcM7+7vj1oyTnwfJ+aBjnDgwJYefvlDi7R6B4CDglI78UL5raiBN/p83iFGp7nxzxff14r6Qowr6DqD8Dq6ezQWGZNKwCwuwdS+5pdGAMNjWPA7hVl39941VDpwAm/Ml9cYLVMGXTo2a6ZmAPwm+GNFtlDOkt/x/DJ8vff1HxIuVDFAkNa6AbIZm70L/HtCZxWx/DDj585gx8AZPX8LZfOVNaDhdndp1bKGdGAFhH9Pm+BM68ndk9DmCeFsINCSottu/5uoLv+0wsm1+5q6H9A2IVRVgYuOvCcFZvhpwEIugNrGk8Kgw7wIx1oNSdiK7dXo3CGL0phPcPX80Cy2AGHYaaR6NOBngUBg6kqc2rdqitIymBxVnjpjBxKgA3qW8nf7kLoycikt2BvgGKnbeS6hBDD8P4cqwKPP+5fmW5gyeKUNzAmufyr+D3Y7Ci2ZrQ8uGQ6Ucws0Q1UdVuKmLzssl3bzWXGreB970M+/LlBUGvp47R03StxlyIXaFWQ0uMeOtf09ui6QO7MtKCEFPCERon7xTkfNACeTjacViEDV+faO2m0akcmuEfn2Z8T80k+InIDzMNF++683M4hYQdZki4gMx493R7lwFaTDOsL61urE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
